token:
  expiration_time: 864000000
  secret: '{cipher}AQA0cRBJQ6EG1FcuQzrVMLP4AFYps1gOFsm2f92XePjdOXey1HkhuGPZX+tOt/QJdLhIGTMy2GprfjCU3n55g6dH+U+k+Z4kDR6iADw3FPR8XN9qxsFAcxRUMN4t0rrnHIvGsjMtZM0WqV87Vz57e5nYuXLFl6wZuhcglPNJBTc3IszStjn+SunF1aufk5euGTz5GDXhMPWr6M5gfhGLhXzrGhjd9lapFfYNHNtIA/GxpJzAgcpQBTauaPRTHsu+aopGcnQdRdxLz1yt970tcID8srbJ5RK2MpRj2uuzcfHomNj7oMKiP2wvSNUpLgQYa48b+/wA1y7qgl3G0nSOJqXgM9jMBdA/fM4GPZDVx6O/nMySRVGZeDVHit66+uBGhPJGoL+S0YtB9oGIevAMSCGP'

gateway:
  ip: 192.168.114.5